### ISSUE TITLE
Configuration/Design Question

### ISSUE THREAD

**Issue by hurrells-ca** [open-start/opentheme#11]
Hello. I like the theme but having problems customizing. Check out hurrells-ca.github.io.

20151002: First problems are:
- I am a new user of jekyll and github. I have the basics figured out but am not a website coder.
- Not able to locate header material above contents of index.html. Header-3d seems to be in css/main.min.css but that file is un-readable and difficult to edit.
- Where is the mailchimp integration and how do I get rid of that header part?
- The rest of index.html is pretty understandable and editable.
- Is there a clean version?

20151002: Uncompressed main.min.css & starting to understand _config.yml.
- I have uncompressed main.min.css now so that I can edit it as needed.
- Starting to customize _config.yml.

20151003: I just figured out the stuff I want to change is in the _includes dir.
- Editing a bunch of stuff in _includes header.html, footer.html
- I think I like this code....

**Comment by manavsehgal** [comment]
I am glad you documented your journey... I will try to update the theme docs accordingly.
- To understand how all files are organised start with `gulpfile.js`
- Uncompressed styles are in `_sass` folder
- Reusable components are in `_includes`
- Page templates in `_layouts` 
- Uncompressed JS in `coffee` folder

**Comment by hurrells-ca** [comment]
Hello

Thank you for your response and explaination.  They will help a beginner
like me.

I like your code and will be using your theme.

Thank you
Steve
