### ISSUE TITLE
gulp: command not found

### ISSUE THREAD

**Issue by JOduMonT** [open-start/opentheme#12]
Hi;
I know it's for sure my lack of knowledge of those techno but
I'm using NPM 1.3.10 on Ubuntu 14.04 with Ruby 2.3.0
i'd followed this step 

```
For local use with gulp
Install gulp-install as a development dependency:
npm install --save-dev gulp-install
```

which I found here : https://www.npmjs.com/package/gulp-install

when i'm at the root of openthemes project and launch gulp as you mention into your README.md
I have gulp : command not found.

Thanks for your help!

Jonathan

**Comment by manavsehgal** [comment]
You need to do this...

```
npm install --global gulp-cli
```

**Comment by JOduMonT** [comment]
Sadly it's going to another issue

_throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`?');_

which I fixed by 

```
rm -rf node_modules
npm install
```

but now gulp said Cannot find module 'gulp-sass'
I'd followed [Getting Started Gulp + SasS](http://ryanchristiani.com/getting-started-with-gulp-and-sass/) without success.

As you probably figure this is my first experience with Gulp

...
Actually, I just want to use your theme on Jekyll
So I clone your code into a dir and serve it with Jekyll == it's works and make me happy!!
Do you have any CONS for this method ?

**Comment by manavsehgal** [comment]
try also installing gulp as a dev dependency.

npm install --save-dev gulp
