### ISSUE TITLE
Does the Jekyll flash plugin work?

### ISSUE THREAD

**Issue by mspanish** [open-start/opentheme#2]
I see you've already integrated the very cool YouTube iframe based plugin. Awesome. But how about  the Flash one? Sad reality for many of us devs is that we still have a ton of Flash based content. In my case, this new site is dedicated to showcasing all my old junk for free, whereas my new sites are all HTML5. 

I'll try using the current Jekyll flash plugin and post any results here, but wondered if you've thought of doing an integration directly in your OpenTheme plugins.

**Comment by mspanish** [comment]
I did not have success with this plugin, but embedding Flash directly using swfobject works - I guess if you need to embed your flash in blog posts or something you would be out of luck, but for my purposes embedding directly in the HTML should be fine. Would be great to see a plugin nonetheless, although I understand people don't have a lot of motivation to develop for Flash unless they are in e-learning where it's a bit hard to escape it.

**Comment by manavsehgal** [comment]
I won't recommend using Jekyll plugins, unless these work in --safe compilation mode. This way you can skip the Jekyll/Gulp process all together and "code/change" your site source directly in GitHub. GitHub will compile the Pages if you are using only supported plugins.
